local achievements = {}


--achievements["Welcome"] = {
--	ImageId = 6915066359; -- ID of the achievement's image
--	Description = "Thanks for playing the game!"; -- The description for this achievement
	
--	OrderRank = 1; -- The position this achievement will appear on the GUI
--}

--achievements["10 minutes"] = {
--	ImageId = 228648990;
--	Description = "You've played for 10 minutes. Keep going!";
--	OrderRank = 2;
--}

--achievements["Energetic"] = {
--	ImageId = 541620958;
--	Description = "You're quite energetic to have walked 500 studs already!";
--	OrderRank = 3;
--}

achievements["H"] = {
	Title = "Hydrogen";
	ImageId = 6915066359;
	Description = "You got a Hydrogen Atom!";
	OrderRank = 1;
}

achievements["He"] = {
	Title = "Heilum";
	ImageId = 6915066359;
	Description = "You got a Helium Atom!";
	OrderRank = 2;
}

achievements["Li"] = {
	Title = "Lithium";
	ImageId = 6915066359;
	Description = "You got a Lithium Atom!";
	OrderRank = 3;
}

achievements["Be"] = {
	Title = "Beryllium";
	ImageId = 6915066359;
	Description = "You got a Beryllium Atom!";
	OrderRank = 4;
}

achievements["B"] = {
	Title = "Boron";
	ImageId = 6915066359;
	Description = "You got a Boron Atom!";
	OrderRank = 5;
}

achievements["C"] = {
	Title = "Carbon";
	ImageId = 6915066359;
	Description = "You got a Carbon Atom!";
	OrderRank = 6;
}

achievements["N"] = {
	Title = "Nitrogen";
	ImageId = 6915066359;
	Description = "You got a Nitrogen Atom!";
	OrderRank = 7;
}

achievements["O"] = {
	Title = "Oxygen";
	ImageId = 6915066359;
	Description = "You got a Oxygen Atom!";
	OrderRank = 8;
}

achievements["F"] = {
	Title = "Fluorine";
	ImageId = 6915066359;
	Description = "You got a Fluorine Atom!";
	OrderRank = 9;
}

achievements["Ne"] = {
	Title = "Neon";
	ImageId = 6915066359;
	Description = "You got a Neon Atom!";
	OrderRank = 10;
}

achievements["Na"] = {
	Title = "Sodium";
	ImageId = 6915066359;
	Description = "You got a Sodium Atom!";
	OrderRank = 11;
}

achievements["Mg"] = {
	Title = "Magnesium";
	ImageId = 6915066359;
	Description = "You got a Magnesium Atom!";
	OrderRank = 12;
}

achievements["Al"] = {
	Title = "Aluminium";
	ImageId = 6915066359;
	Description = "You got a Aluminium Atom!";
	OrderRank = 13;
}

achievements["Si"] = {
	Title = "Silicon";
	ImageId = 6915066359;
	Description = "You got a Silicon Atom!";
	OrderRank = 14;
}

achievements["P"] = {
	Title = "Phosphorus";
	ImageId = 6915066359;
	Description = "You got a Phosphorus Atom!";
	OrderRank = 15;
}

achievements["S"] = {
	Title = "Sulfur";
	ImageId = 6915066359;
	Description = "You got a Sulfur Atom!";
	OrderRank = 16;
}

achievements["Cl"] = {
	Title = "Chlorine";
	ImageId = 6915066359;
	Description = "You got a Chlorine Atom!";
	OrderRank = 17;
}

achievements["Ar"] = {
	Title = "Argon";
	ImageId = 6915066359;
	Description = "You got a Argon Atom!";
	OrderRank = 18;
}

achievements["K"] = {
	Title = "Potassium";
	ImageId = 6915066359;
	Description = "You got a Potassium Atom!";
	OrderRank = 19;
}

achievements["Ca"] = {
	Title = "Calcium";
	ImageId = 6915066359;
	Description = "You got a Calcium Atom!";
	OrderRank = 20;
}

achievements["Sc"] = {
	Title = "Scandium";
	ImageId = 6915066359;
	Description = "You got a Scandium Atom!";
	OrderRank = 21;
}

achievements["Ti"] = {
	Title = "Titanium";
	ImageId = 6915066359;
	Description = "You got a Titanium Atom!";
	OrderRank = 22;
}

achievements["V"] = {
	Title = "Vanadium";
	ImageId = 6915066359;
	Description = "You got a Vanadium Atom!";
	OrderRank = 23;
}

achievements["Cr"] = {
	Title = "Chromium";
	ImageId = 6915066359;
	Description = "You got a Chromium Atom!";
	OrderRank = 24;
}

achievements["Mn"] = {
	Title = "Manganese";
	ImageId = 6915066359;
	Description = "You got a Manganese Atom!";
	OrderRank = 25;
}

achievements["Fe"] = {
	Title = "Iron";
	ImageId = 6915066359;
	Description = "You got a Iron Atom!";
	OrderRank = 26;
}

achievements["Co"] = {
	Title = "Cobalt";
	ImageId = 6915066359;
	Description = "You got a Cobalt Atom!";
	OrderRank = 27;
}

achievements["Ni"] = {
	Title = "Nickel";
	ImageId = 6915066359;
	Description = "You got a Nickel Atom!";
	OrderRank = 28;
}

achievements["Cu"] = {
	Title = "Copper";
	ImageId = 6915066359;
	Description = "You got a Copper Atom!";
	OrderRank = 29;
}

achievements["Zn"] = {
	Title = "Zinc";
	ImageId = 6915066359;
	Description = "You got a Zinc Atom!";
	OrderRank = 30;
}

achievements["Ga"] = {
	Title = "Gallium";
	ImageId = 6915066359;
	Description = "You got a Gallium Atom!";
	OrderRank = 31;
}

achievements["Ge"] = {
	Title = "Germanium";
	ImageId = 6915066359;
	Description = "You got a Germanium Atom!";
	OrderRank = 32;
}

achievements["As"] = {
	Title = "Arsenic";
	ImageId = 6915066359;
	Description = "You got a Arsenic Atom!";
	OrderRank = 33;
}

achievements["Se"] = {
	Title = "Selenium";
	ImageId = 6915066359;
	Description = "You got a Selenium Atom!";
	OrderRank = 34;
}

achievements["Br"] = {
	Title = "Bromine";
	ImageId = 6915066359;
	Description = "You got a Bromine Atom!";
	OrderRank = 35;
}

achievements["Kr"] = {
	Title = "Krypton";
	ImageId = 6915066359;
	Description = "You got a Krypton Atom!";
	OrderRank = 36;
}

achievements["Rb"] = {
	Title = "Rubidium";
	ImageId = 6915066359;
	Description = "You got a Rubidium Atom!";
	OrderRank = 37;
}

achievements["Sr"] = {
	Title = "Strontium";
	ImageId = 6915066359;
	Description = "You got a Strontium Atom!";
	OrderRank = 38;
}

achievements["Y"] = {
	Title = "Yttrium";
	ImageId = 6915066359;
	Description = "You got a Yttrium Atom!";
	OrderRank = 39;
}

achievements["Zr"] = {
	Title = "Zirconium";
	ImageId = 6915066359;
	Description = "You got a Zirconium Atom!";
	OrderRank = 40;
}

achievements["Nb"] = {
	Title = "Niobium";
	ImageId = 6915066359;
	Description = "You got a Niobium Atom!";
	OrderRank = 41;
}

achievements["Mo"] = {
	Title = "Molybdenum";
	ImageId = 6915066359;
	Description = "You got a Molybdenum Atom!";
	OrderRank = 42;
}

achievements["Tc"] = {
	Title = "Technetium";
	ImageId = 6915066359;
	Description = "You got a Technetium Atom!";
	OrderRank = 43;
}

achievements["Ru"] = {
	Title = "Ruthenium";
	ImageId = 6915066359;
	Description = "You got a Ruthenium Atom!";
	OrderRank = 44;
}

achievements["Rh"] = {
	Title = "Rhodium";
	ImageId = 6915066359;
	Description = "You got a Rhodium Atom!";
	OrderRank = 45;
}

achievements["Pd"] = {
	Title = "Palladium";
	ImageId = 6915066359;
	Description = "You got a Palladium Atom!";
	OrderRank = 46;
}

achievements["Ag"] = {
	Title = "Silver";
	ImageId = 6915066359;
	Description = "You got a Silver Atom!";
	OrderRank = 47;
}

achievements["Cd"] = {
	Title = "Cadmium";
	ImageId = 6915066359;
	Description = "You got a Cadmium Atom!";
	OrderRank = 48;
}

achievements["In"] = {
	Title = "Indium";
	ImageId = 6915066359;
	Description = "You got a Indium Atom!";
	OrderRank = 49;
}

achievements["Sn"] = {
	Title = "Tin";
	ImageId = 6915066359;
	Description = "You got a Tin Atom!";
	OrderRank = 50;
}

achievements["Sb"] = {
	Title = "Antimony";
	ImageId = 6915066359;
	Description = "You got a Antimony Atom!";
	OrderRank = 51;
}

achievements["Te"] = {
	Title = "Tellurium";
	ImageId = 6915066359;
	Description = "You got a Tellurium Atom!";
	OrderRank = 52;
}

achievements["I"] = {
	Title = "Iodine";
	ImageId = 6915066359;
	Description = "You got a Iodine Atom!";
	OrderRank = 53;
}

achievements["Xe"] = {
	Title = "Xenon";
	ImageId = 6915066359;
	Description = "You got a Xenon Atom!";
	OrderRank = 54;
}

achievements["Cs"] = {
	Title = "Cesium";
	ImageId = 6915066359;
	Description = "You got a Cesium Atom!";
	OrderRank = 55;
}

achievements["Ba"] = {
	Title = "Barium";
	ImageId = 6915066359;
	Description = "You got a Barium Atom!";
	OrderRank = 56;
}

achievements["La"] = {
	Title = "Lanthanum";
	ImageId = 6915066359;
	Description = "You got a Lanthanum Atom!";
	OrderRank = 57;
}

achievements["Ce"] = {
	Title = "Cerium";
	ImageId = 6915066359;
	Description = "You got a Cerium Atom!";
	OrderRank = 58;
}

achievements["Pr"] = {
	Title = "Praseodymium";
	ImageId = 6915066359;
	Description = "You got a Praseodymium Atom!";
	OrderRank = 59;
}

achievements["Nd"] = {
	Title = "Neodymium";
	ImageId = 6915066359;
	Description = "You got a Neodymium Atom!";
	OrderRank = 60;
}

achievements["Pm"] = {
	Title = "Promethium";
	ImageId = 6915066359;
	Description = "You got a Promethium Atom!";
	OrderRank = 61;
}

achievements["Sm"] = {
	Title = "Samarium";
	ImageId = 6915066359;
	Description = "You got a Samarium Atom!";
	OrderRank = 62;
}

achievements["Eu"] = {
	Title = "Europium";
	ImageId = 6915066359;
	Description = "You got a Europium Atom!";
	OrderRank = 63;
}

achievements["Gd"] = {
	Title = "Gadolinium";
	ImageId = 6915066359;
	Description = "You got a Gadolinium Atom!";
	OrderRank = 64;
}

achievements["Tb"] = {
	Title = "Terbium";
	ImageId = 6915066359;
	Description = "You got a Terbium Atom!";
	OrderRank = 65;
}

achievements["Dy"] = {
	Title = "Dysprosium";
	ImageId = 6915066359;
	Description = "You got a Dysprosium Atom!";
	OrderRank = 66;
}

achievements["Ho"] = {
	Title = "Holmium";
	ImageId = 6915066359;
	Description = "You got a Holmium Atom!";
	OrderRank = 67;
}

achievements["Er"] = {
	Title = "Erbium";
	ImageId = 6915066359;
	Description = "You got a Erbium Atom!";
	OrderRank = 68;
}

achievements["Tm"] = {
	Title = "Thulium";
	ImageId = 6915066359;
	Description = "You got a Thulium Atom!";
	OrderRank = 69;
}

achievements["Yb"] = {
	Title = "Ytterbium";
	ImageId = 6915066359;
	Description = "You got a Ytterbium Atom!";
	OrderRank = 70;
}

achievements["Lu"] = {
	Title = "Lutetium";
	ImageId = 6915066359;
	Description = "You got a Lutetium Atom!";
	OrderRank = 71;
}

achievements["Hf"] = {
	Title = "Hafnium";
	ImageId = 6915066359;
	Description = "You got a Hafnium Atom!";
	OrderRank = 72;
}

achievements["Ta"] = {
	Title = "Tantalum";
	ImageId = 6915066359;
	Description = "You got a Tantalum Atom!";
	OrderRank = 73;
}

achievements["W"] = {
	Title = "Tungsten";
	ImageId = 6915066359;
	Description = "You got a Tungsten Atom!";
	OrderRank = 74;
}

achievements["Re"] = {
	Title = "Rhenium";
	ImageId = 6915066359;
	Description = "You got a Rhenium Atom!";
	OrderRank = 75;
}

achievements["Os"] = {
	Title = "Osmium";
	ImageId = 6915066359;
	Description = "You got a Osmium Atom!";
	OrderRank = 76;
}

achievements["Ir"] = {
	Title = "Iridium";
	ImageId = 6915066359;
	Description = "You got a Iridium Atom!";
	OrderRank = 77;
}

achievements["Pt"] = {
	Title = "Platinum";
	ImageId = 6915066359;
	Description = "You got a Platinum Atom!";
	OrderRank = 78;
}

achievements["Au"] = {
	Title = "Gold";
	ImageId = 6915066359;
	Description = "You got a Gold Atom!";
	OrderRank = 79;
}

achievements["Hg"] = {
	Title = "Mercury";
	ImageId = 6915066359;
	Description = "You got a Mercury Atom!";
	OrderRank = 80;
}

achievements["Tl"] = {
	Title = "Thallium";
	ImageId = 6915066359;
	Description = "You got a Thallium Atom!";
	OrderRank = 81;
}

achievements["Pb"] = {
	Title = "Lead";
	ImageId = 6915066359;
	Description = "You got a Lead Atom!";
	OrderRank = 82;
}

achievements["Bi"] = {
	Title = "Bismuth";
	ImageId = 6915066359;
	Description = "You got a Bismuth Atom!";
	OrderRank = 83;
}

achievements["Po"] = {
	Title = "Polonium";
	ImageId = 6915066359;
	Description = "You got a Polonium Atom!";
	OrderRank = 84;
}

achievements["At"] = {
	Title = "Astatine";
	ImageId = 6915066359;
	Description = "You got a Astatine Atom!";
	OrderRank = 85;
}

achievements["Rn"] = {
	Title = "Radon";
	ImageId = 6915066359;
	Description = "You got a Radon Atom!";
	OrderRank = 86;
}

achievements["Fr"] = {
	Title = "Francium";
	ImageId = 6915066359;
	Description = "You got a Francium Atom!";
	OrderRank = 87;
}

achievements["Ra"] = {
	Title = "Radium";
	ImageId = 6915066359;
	Description = "You got a Radium Atom!";
	OrderRank = 88;
}

achievements["Ac"] = {
	Title = "Actinium";
	ImageId = 6915066359;
	Description = "You got a Actinium Atom!";
	OrderRank = 89;
}

achievements["Th"] = {
	Title = "Thorium";
	ImageId = 6915066359;
	Description = "You got a Thorium Atom!";
	OrderRank = 90;
}

achievements["Pa"] = {
	Title = "Protactinium";
	ImageId = 6915066359;
	Description = "You got a Protactinium Atom!";
	OrderRank = 91;
}

achievements["U"] = {
	Title = "Uranium";
	ImageId = 6915066359;
	Description = "You got a Uranium Atom!";
	OrderRank = 92;
}

achievements["Np"] = {
	Title = "Neptunium";
	ImageId = 6915066359;
	Description = "You got a Neptunium Atom!";
	OrderRank = 93;
}

achievements["Pu"] = {
	Title = "Plutonium";
	ImageId = 6915066359;
	Description = "You got a Plutonium Atom!";
	OrderRank = 94;
}

achievements["Am"] = {
	Title = "Americium";
	ImageId = 6915066359;
	Description = "You got a Americium Atom!";
	OrderRank = 95;
}

achievements["Cm"] = {
	Title = "Curium";
	ImageId = 6915066359;
	Description = "You got a Curium Atom!";
	OrderRank = 96;
}

achievements["Bk"] = {
	Title = "Berkelium";
	ImageId = 6915066359;
	Description = "You got a Berkelium Atom!";
	OrderRank = 97;
}

achievements["Cf"] = {
	Title = "Californium";
	ImageId = 6915066359;
	Description = "You got a Californium Atom!";
	OrderRank = 98
}

achievements["Es"] = {
	Title = "Einsteinium";
	ImageId = 6915066359;
	Description = "You got a Einsteinium Atom!";
	OrderRank = 99;
}

achievements["Fm"] = {
	Title = "Fermium";
	ImageId = 6915066359;
	Description = "You got a Fermium Atom!";
	OrderRank = 100;
}

achievements["Md"] = {
	Title = "Mendelevium";
	ImageId = 6915066359;
	Description = "You got a Mendelevium Atom!";
	OrderRank = 101;
}

achievements["No"] = {
	Title = "Nobelium";
	ImageId = 6915066359;
	Description = "You got a Nobelium Atom!";
	OrderRank = 102;
}

achievements["Lr"] = {
	Title = "Lawrencium";
	ImageId = 6915066359;
	Description = "You got a Lawrencium Atom!";
	OrderRank = 103;
}

achievements["Rf"] = {
	Title = "Rutherfordium";
	ImageId = 6915066359;
	Description = "You got a Rutherfordium Atom!";
	OrderRank = 104;
}

achievements["Db"] = {
	Title = "Dubnium";
	ImageId = 6915066359;
	Description = "You got a Dubnium Atom!";
	OrderRank = 105;
}

achievements["Sg"] = {
	Title = "Seaborgium";
	ImageId = 6915066359;
	Description = "You got a Seaborgium Atom!";
	OrderRank = 106;
}

achievements["Bh"] = {
	Title = "Bohrium";
	ImageId = 6915066359;
	Description = "You got a Bohrium Atom!";
	OrderRank = 107;
}

achievements["Hs"] = {
	Title = "Hassium";
	ImageId = 6915066359;
	Description = "You got a Hassium Atom!";
	OrderRank = 108;
}

achievements["Mt"] = {
	Title = "Meitnerium";
	ImageId = 6915066359;
	Description = "You got a Meitnerium Atom!";
	OrderRank = 109;
}

achievements["Ds"] = {
	Title = "Darmstadtium";
	ImageId = 6915066359;
	Description = "You got a Darmstadtium Atom!";
	OrderRank = 110;
}

achievements["Rg"] = {
	Title = "Roentgenium";
	ImageId = 6915066359;
	Description = "You got a Roentgenium Atom!";
	OrderRank = 111;
}

achievements["Cn"] = {
	Title = "Copernicium";
	ImageId = 6915066359;
	Description = "You got a Copernicium Atom!";
	OrderRank = 112;
}

achievements["Nh"] = {
	Title = "Nihonium";
	ImageId = 6915066359;
	Description = "You got a Nihonium Atom!";
	OrderRank = 113;
}

achievements["Fl"] = {
	Title = "Flerovium";
	ImageId = 6915066359;
	Description = "You got a Flerovium Atom!";
	OrderRank = 114;
}

achievements["Mc"] = {
	Title = "Moscovium";
	ImageId = 6915066359;
	Description = "You got a Moscovium Atom!";
	OrderRank = 115;
}

achievements["Lv"] = {
	Title = "Livermorium";
	ImageId = 6915066359;
	Description = "You got a Livermorium Atom!";
	OrderRank = 116;
}

achievements["Ts"] = {
	Title = "Tennessine";
	ImageId = 6915066359;
	Description = "You got a Tennessine Atom!";
	OrderRank = 117;
}

achievements["Og"] = {
	Title = "Oganesson";
	ImageId = 6915066359;
	Description = "You got a Oganesson Atom!";
	OrderRank = 118;
}

return achievements;

